import { GoogleSpreadsheet } from "google-spreadsheet";

async function run() {
  // Initialize the sheet - doc ID is the long id in the sheets URL
  // google-workspace-code-playground/sheets1 on natankrasney@gmail.com

  const doc = new GoogleSpreadsheet("1god9TP9YRgm3wGljfzjvLzq8UGlx395ZBZ5r90E9-6M");

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    //   client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    //   private_key: process.env.GOOGLE_PRIVATE_KEY,
    client_email:
      "service-google-sheets-api-samp@serious-fabric-378409.iam.gserviceaccount.com",
    private_key:
      "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDDfE7OBzSntuKN\nOK03OKRxeJmiHfj3w9rpB5Ck40PnUkGykZNFcRoD6u4CLH6kxw1oLrdCXdjZSttv\nH8cF+2rGo+89vtiWep0f9UJH1vflnPIKQMIcROeRcoT3gRhGy+ET9wTAYTpB6ivT\neknzlk9+o/3SYa/KGcurSMrZsJIEZXpiEWHFQZHG3tHCNIgrkcyEbaEIujK0I0sR\nH2N/F+iWtS6ZVneUadqVPufcX1Ghy7d2EcFuRxWh/KTwoKiiCi+INIaKePMPmY2N\ne3AjBfz4LO431jTyurWT884CtbjLfDx2HmKWWRYxKYmp3A+TPERuoxSbwgj+s29E\n34ir0NVXAgMBAAECggEAYL66eXhTdNUr1dxAzV149LdMwVC4EFablkwqJ5BZ4Ldy\n0B7/lZRd3aZ82BKRMpdYaUEFbRDo6tEDPEGry6gbtecX1aUHp6FS9af5f3hCAx7j\nInPeHQN03ySf7aW0EAWChNDxRwxXOpvbyLNyudyfxvr9+QpjZ0/Q3hoOWiHqgcWh\nDJjwGeLOsMgebK3ytzeOVcTvVa3JQC8dWJ/AMfFHC5SJSJl5xf3VihIoHOSLSZp8\nJ85LS8kVs9Y9TIawEUf6p0pqFQjsA9VJeq5ybaUrMkI8JwMC80t61xJDDvZCYPDE\nU9SWRVZ3k426rsp5dK/ZNj+LcX+z005wf/mUlJHE4QKBgQDwADdGEA+vi2EHOsu2\nG7g8VOmI1pAGIlHOdh7yMbr3/1t2kztb6g//15icUQ72t1xwy7s5w2cwi8RrhN+g\n7r7B4IJWo+3YDDNj8iZXiHh2VeY+98MzR5yGCXrRUKwTy21wTp4qMfvnxucihDEw\nK0PNxwRVWHYIFTkS5j8qs9MjiQKBgQDQhGhNWROyT0PEtqNP5d98iZibg5hqXySG\nOJ2FispH7YdtkY11TU/dnVaXMp+dX41VlK0bYCQgJn7PVWa64uubwXNA8BoJ4S5F\nIzvciaIu2l4vwOTROBUntO2QoZwklpVIiuG2lcyzlbUqIWl0Ne9K7VMeidG7NZRo\nugq+b2iZ3wKBgGn2PnExkCtaJ0mw3NYXYP1KJB2lVctPhbzZDAq0iC8MUE6G7LNF\nITE8+AU0CJ5HEIpAePYk3r9hRiSOcsmz/wbMX99u2wkDQgFDnUgSWdUtUc3FSCqw\n2FuZfd9Cdeb7buMh4tUQYn7Po6bqpGj3ASWuU6x2tQ4WiK9eds8cvAC5AoGBAMWA\nlLamp8Rd1ceuYnOcPRndzoGGnMgsRBEp8PH7auvELWF32y//QaWckNb3qT3Lsrgb\n8fcbEjytmbFSp9Jee2H1UvBwO4meE1CDNgEHEGomhc3ffBw7bbZFZjt3B8mUI+Qp\nP+/MZa64H3e/W/4p0/T5Y6BqVBBpiJ/Fj8WfCsmrAoGAG4ZIYT8Iy3VXj9QQtByu\nfaAQY2Aiiot/6Qnci4oIB26agxhOt2tGDVfVTXz2gkDtR4FQvsgUB+N8cwmecFu+\n+MDRdl8iHCLrzTc9ya50rSEHXeLWaZUCWi7dqfvSEGNVESM0RFQ9BsJSmRRopH/S\nEm4BgHJFYXwWZgcUnTrabzA=\n-----END PRIVATE KEY-----\n",
  });

  await doc.loadInfo(); // loads document properties and worksheets
  console.log(doc.title);
}

run();
